export const TRENDING_MEALS = [
  {
    id: 'trending-chicken-curry',
    title: 'Easy chicken curry',
    cuisine: 'Indian-inspired',
    mood: 'Comfort',
    cookingMinutes: 50,
    caloriesPerServing: 354,
    sourceName: 'Good Food',
    sourceUrl: 'https://www.bbcgoodfood.com/recipes/easy-chicken-curry',
    sourceVerified: true,
    displayImageUrl: '/images/trending/chicken-curry.jpg',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Chicken_curry.jpg',
    imageSourceUrl: 'https://commons.wikimedia.org/wiki/File:Chicken_curry.jpg',
    imageLicenseType: 'CC BY-SA 2.0',
    imageLicenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0/',
    imageAttributionRequirements: 'Photo: Quadell / Wikimedia Commons · CC BY-SA 2.0',
    imageRightsStatus: 'VerifiedCommercial',
    imageProvider: 'Wikimedia Commons',
    imageCreator: 'Quadell',
    imageCommercialUseAllowed: true,
    imageAttributionRequired: true,
    imageVerified: true,
  },
  {
    id: 'trending-shakshuka',
    title: 'Shakshuka',
    cuisine: 'North African',
    mood: 'Vibrant',
    cookingMinutes: 25,
    caloriesPerServing: 340,
    sourceName: 'Good Food',
    sourceUrl: 'https://www.bbcgoodfood.com/recipes/shakshuka',
    sourceVerified: true,
    displayImageUrl: '/images/trending/shakshuka.jpg',
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/Shakshuka_Dish.jpg/960px-Shakshuka_Dish.jpg',
    imageSourceUrl: 'https://commons.wikimedia.org/wiki/File:Shakshuka_Dish.jpg',
    imageLicenseType: 'CC BY 4.0',
    imageLicenseUrl: 'https://creativecommons.org/licenses/by/4.0/',
    imageAttributionRequirements: 'Photo: Junbinhuang / Wikimedia Commons · CC BY 4.0',
    imageRightsStatus: 'VerifiedCommercial',
    imageProvider: 'Wikimedia Commons',
    imageCreator: 'Junbinhuang',
    imageCommercialUseAllowed: true,
    imageAttributionRequired: true,
    imageVerified: true,
  },
  {
    id: 'trending-lasagne',
    title: 'Easy classic lasagne',
    cuisine: 'Italian',
    mood: 'Elegant',
    cookingMinutes: 75,
    caloriesPerServing: 844,
    sourceName: 'Good Food',
    sourceUrl: 'https://www.bbcgoodfood.com/recipes/classic-lasagne',
    sourceVerified: true,
    displayImageUrl: '/images/trending/lasagne.jpg',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Lasagna_food.jpg',
    imageSourceUrl: 'https://commons.wikimedia.org/wiki/File:Lasagna_food.jpg',
    imageLicenseType: 'Public Domain',
    imageLicenseUrl: null,
    imageAttributionRequirements: 'Public-domain photo: Jon Sullivan / Wikimedia Commons',
    imageRightsStatus: 'VerifiedCommercial',
    imageProvider: 'Wikimedia Commons',
    imageCreator: 'Jon Sullivan',
    imageCommercialUseAllowed: true,
    imageAttributionRequired: false,
    imageVerified: true,
  },
]
